### ISSUE TITLE
FIX: 반납 진행 중 반납 모달 바깥을 클릭 시 반납 진행이 취소됨

### ISSUE THREAD

**Issue by scarf005** [jiphyeonjeon-42/frontend#297]
## description
> 실수로 바깥을 누를 시 진행이 초기화되므로, 취소 기능을 제거하는 것이 좋을 것 같습니다.

![_03](https://user-images.githubusercontent.com/54838975/201286701-82063716-332e-45cf-9d24-0cd231d64510.png)

**Comment by YeonSeong-Lee** [comment]
사용자의 편의를 위해 추가되어있는것으로 남기는게 더 적절할거 같습니다.
