### ISSUE TITLE
첫 페이지 검색 오류

### ISSUE THREAD

**Issue by AYoungSn** [jiphyeonjeon-42/frontend#428]
### 재현 방법

홈페이지에서 `C++` 을 검색하면 `C  ` 로 검색된 결과가 보여집니다.

### 추가 정보

한번 검색한 이후에 나오는 페이지에서는 `C++` 검색 시 입력한 `C++` 그대로 검색이 가능합니다.

사이트 이용 중 이슈를 발견하여 알려드립니다! 👍🏻

**Comment by chanhihi** [comment]
우선 오류 제보에 감사드립니다. 이러한 문제 발생에 대해 불편을 드려 죄송합니다. 🙇‍♂️ 

첫페이지에서 검색시 검색되는 단어들이 utf-8 Encoding 을 거치지 않고 처리되는 것을 확인 하였습니다. 

검색 시 utf-8 인코딩을 거치지 않고 문자열로 들어가는 것은 검색 엔진의 설정이나 처리 방식에 문제가 있을 수 있습니다.

해당 사항은 백엔드 개발자들과 논의 해보고 반영토록 하겠습니다. 

다시 한번 오류 제보에 감사드리며, 좋은 하루 되시길 바라겠습니다. 🙏

**Comment by chanhihi** [comment]
https://github.com/jiphyeonjeon-42/frontend/blob/62278a335589a14250bb3bc24ea9e727c0cb0f52/src/component/utils/SearchBar.tsx#L40-L44

42L, 43L 사이에 인코딩 한줄 추가로 해결 될 것 같습니다. 

`const encodedUri = encodeURIComponent(searchWord);`
