### ISSUE TITLE
일반 회원가입시 42 이메일로 로그인 가능함

### ISSUE THREAD

**Issue by scarf005** [jiphyeonjeon-42/frontend#478]
### 기능 설명

회의록: https://www.collabee.co/project/163329/issue/postDetail/2356140

- 42 이메일로 일반 회원가입시 타 카뎃을 사칭할 수 있습니다.
- 백엔드에서는 적용 예정입니다. https://github.com/jiphyeonjeon-42/backend/pull/540
- 프론트에서도 일반 회원가입 UI에서 적용해야 합니다.

```[tasklist]
### 일반 회원가입 UI
- [ ] https://github.com/jiphyeonjeon-42/backend/pull/540
- [ ] 42 이메일일 시 제출 버튼 비활성화
- [ ] 42 이메일일 시 오류 메시지 표시
- [ ] `STUDENT_42_SUBSCRIPTION_FORBIDDEN` 처리
```

**Comment by notusing11** [comment]
이후 회의때 이메일 회원가입을 아예 폐기하고 소셜 로그인으로 전환하자고 정리되었습니다
곧 없어질 기능이라 다른 기능 및 수정 작업에 집중하시면 좋을 것 같습니다~ 

관련 회의록 : https://www.collabee.co/project/163329/issue/postDetail/2388168
