### ISSUE TITLE
상세페이지에서 바로 에러 다이얼로그 두개 노출되는 문제

### ISSUE THREAD

**Issue by notusing11** [jiphyeonjeon-42/frontend#489]
### 재현 방법

1. 아무책을 골라 상세페이지를 들어간다
2. 두개 다이얼로그가 항상 뜸
 - Cannot read properties of undefined (reading 'isLiked')
 - 10자 이상 420자 이하로 입력해주세요.

**Comment by scarf005** [comment]
#470 에서 `localStorage.getItem()` 에 [`|| ""` 을 추가하는 과정](https://github.com/jiphyeonjeon-42/frontend/commit/dc85592d9#diff-08f9f82d84d1eecd802203f383d55aa952ad68c486a0aee1dfd91defe759f1b8R15)에서 문제가 발생한 것 같습니다.

```ts
> JSON.parse("")
Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at <anonymous>:2:6
```
