### ISSUE TITLE
태그기록 필터 변경시 네트워크 두번 보냄

### ISSUE THREAD

**Issue by notusing11** [jiphyeonjeon-42/frontend#500]
### 재현 방법

태그기록 페이지 
필터 선택시

**Comment by scarf005** [comment]
https://github.com/jiphyeonjeon-42/frontend/assets/54838975/eddd8232-f302-4386-9a20-e3dac00788ed

버그 재현이 불가능해 재현이 가능해지면 나중에 해결하면 좋을 것 같습니다
