### ISSUE TITLE
메인페이지 검색 바

### ISSUE THREAD

**Issue by chanhihi** [jiphyeonjeon-42/frontend#540]
### 재현 방법

<img width="657" alt="image" src="https://github.com/jiphyeonjeon-42/frontend/assets/85754295/da067048-7014-4867-92cd-b2bd7b85562c">

돋보기 이미지 뒤에 검색이라고 txt가 숨어있는것. 기능일까요 ? 

### 발생 위치

메인페이지

**Comment by chanhihi** [comment]
<img width="571" alt="image" src="https://github.com/jiphyeonjeon-42/frontend/assets/85754295/3509d4e2-c295-43ef-855e-8e9f6c6f0a88">

여기서도 보이긴하네요.

**Comment by scarf005** [comment]
![image](https://github.com/jiphyeonjeon-42/frontend/assets/54838975/7d2fc260-da61-43e5-98d3-8f1a2ffe5c4a)

현재 구현을 확인해 보니 버튼 아이콘을 css 배경 이미지로 구현하고 있어 발생하는 문제인 것 같습니다. 
아이콘을 button 내 svg 태그를 사용하고, 버튼의 속성을 `aria-label="검색"`으로 지정하면 더 시맨틱하게 바꿀 수 있을 것 같습니다.

참고 링크:
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label
- https://gomakethings.com/icon-accessibility-and-aria-label/
