### ISSUE TITLE
절대경로 import 추가

### ISSUE THREAD

**Issue by scarf005** [jiphyeonjeon-42/frontend#541]
### 기능 설명

코드 경로 관리를 수월하게 하기 위해 다음을 이용해 절대경로 import를 추가합니다:

- https://www.typescriptlang.org/tsconfig#paths
- https://github.com/aleclarson/vite-tsconfig-paths

**Comment by notusing11** [comment]
#479  이 이슈는 어떻게 되는 걸까요?
