### ISSUE TITLE
비표준 css 제거

### ISSUE THREAD

**Issue by scarf005** [jiphyeonjeon-42/frontend#544]
### 기능 설명
![_04](https://github.com/jiphyeonjeon-42/frontend/assets/54838975/b59fe17a-d233-4b00-8b5c-323eea286db8)
[![image](https://github.com/jiphyeonjeon-42/frontend/assets/54838975/35e2bf8e-f77c-4c2a-a68f-e0c8601bc9df)](https://browsersl.ist/#q=>0.2%25%0Anot+dead%0Anot+op_mini+all)
[브라우저리스트](https://browsersl.ist/#q=>0.2%25%0Anot+dead%0Anot+op_mini+all)

이미 현대 브라우저에서 transition과 transform을 지원하기 때문에, `-webkit-transition`, `-moz-transform`등의 css 속성을 제거하는 것이 좋을 것 같습니다.

**Comment by notusing11** [comment]
오 생각해보지 못했던 이슈네요! 좋은 의견인 것 같습니다 👍
브라우저 호환성 체크하는 캡처는 어떤 방식으로 확인하신 걸까요? 구경하고 싶습니다!

**Comment by scarf005** [comment]
[브라우저리스트](https://browsersl.ist/#q=%3E0.2%25%0Anot+dead%0Anot+op_mini+all) 홈페이지를 활용했습니다. 이미지에 링크를 달아두긴 했는데, 밑에도 링크를 추가할게요!
