### ISSUE TITLE
[hotfix] 이후 배포부터는 cloudfront를 이용하지 않습니다

### ISSUE THREAD

**Issue by weg901127** [jiphyeonjeon-42/frontend#598]
github action yaml파일을 고쳐야하는데요 클라우드프론트 캐시 무효화하는부분을 누군가 지워주세요...

**Comment by scarf005** [comment]
해당 부분을 통째로 지우면 될까요?

https://github.com/jiphyeonjeon-42/frontend/blob/20c83cc004ca31b8796f9e228ae36026652da468/.github/workflows/deploy-main.yml#L58-L64

**Comment by weg901127** [comment]
<img width="1011" alt="스크린샷 2023-12-23 오후 3 03 34" src="https://github.com/jiphyeonjeon-42/frontend/assets/19397975/34a2112d-2f9c-43e3-8302-9ed95f1b0d07">
이부분이구요 그리고 업로드부분에 sync명령어 --delete옵션 사용해주세요 이정도만 수정 부탁드립니다 맞아요 유킴님

**Comment by weg901127** [comment]
키는 제가 방금 바꿔놨어요

**Comment by not-using** [comment]
https://github.com/jiphyeonjeon-42/frontend/commit/1ec68a2371705ed60df1d9d37cf1dfb532d63417
