### ISSUE TITLE
도서 등록 드랍 다운 버튼

### ISSUE THREAD

**Issue by chanhihi** [jiphyeonjeon-42/frontend#606]
### 재현 방법

도서 등록에서 
신규 도서 카테고리 정보에서 개발 드랍다운 선택이 안됩니다.

### 발생 위치

도서 등록

### 추가 정보

![image](https://github.com/jiphyeonjeon-42/frontend/assets/85754295/0c31a41c-9b5b-4f35-9228-a40eeac36557)

**Comment by not-using** [comment]
이 문제 https://github.com/jiphyeonjeon-42/frontend/pull/595 에서 해결된 내용인데 
develop에만 올라갔고 배포는 아직이라 계속 발견되는 것 같아요

**Comment by chanhihi** [comment]
@not-using 
배포는 언제 어떻게 되는건지 알 수 있을까요
